### ISSUE TITLE
Diagram

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#10]
Provide a diagram that identifies the[ systems engineering view](https://robinagandhi.github.io/swa/slides/lecture-1/systems-security-engineering.html#13) of the software in the hypothetical environment.

**Comment by lreichlinger** [comment]
Added section to Teams Project Proposal and is ready for review on Monday.

**Comment by lreichlinger** [comment]
Uploaded the second version of the Diagram for discussion on Tuesdays meeting. Its called System Engineering View - Version 2.png

**Comment by lreichlinger** [comment]
Had another revision, file called System Engineering View - Version 3.png
