### ISSUE TITLE
Login/MFA Misuse Case

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#23]

**Comment by lreichlinger** [comment]
First draft is uploaded. I wanted to include the Auditing system and research more vulnerabilities that could threaten login or access. I plan to include many more of these for various password threats and use other system elements to help prevent or mitigate threats.

**Comment by lreichlinger** [comment]
I have updated the Software Security Engineering.md file with my example 1 Use-Misuse Case and uploaded version 2 of the diagram to the folder. If someone could please review it that would be great and give me any pointers. I could not figure out how to add a hyperlink in the paragraph to link back to the NextCloud Password Policy @Hinrichsta perhaps you could help me out there.

**Comment by lreichlinger** [comment]
I took MFA out of mine, because @Chepburn-uno had already included it in his Mobile Diagram.
