### ISSUE TITLE
Website Misuse Case

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#24]

**Comment by Hinrichsta** [comment]
Dr. Gandhi's review

- Narrow it down to a single feature
- Make the names realistic

**Comment by Hinrichsta** [comment]
Going to focus on the audit logs within the API

**Comment by Hinrichsta** [comment]
Switched over to Website access

**Comment by Hinrichsta** [comment]
Updated to versions 3 based of a group review last night.  Fixed an error in my lines, added a central focus for the attacker, and gave the attacker a more meaningful name.

**Comment by lreichlinger** [comment]
Yours looks good to me, great work on the paragraphs outlining your Use-Misuse Case, I copied your outline to make it consistent.
