### ISSUE TITLE
Mobile App Misuse Case

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#26]

**Comment by Hinrichsta** [comment]
My review of the work as of 9/22 10:50

- Move the login to Nextcloud as the point that connects to the bad actor, and make the Leaked credentials and the MFA fatigue come from the login bubble.
  - The login to Nextcloud doesn't have any threats, and seems to be weird in the center like that.
- Since moving the login to Nextcloud would take it away from some of the prevents notations they will need to be adjust to the other bubbles.  Maybe add a third malicious bubble, like unsecure MFA (Text or Phone Call)

**Comment by Chepburn-uno** [comment]
Draft 1 - Failed to understand the full scope and concept of the assignment.  After meeting with Dr. Gandhi for the team report out I scrapped this draft and started over.

**Comment by Chepburn-uno** [comment]
Conversation with Professor.

Chris - So we are doing NextCloud and my use case is Mobile Device (android mobile app to access files on nextcloud for a bank). I had a large and complex diagram before yesterdays team meeting with you which I have gone back and parsed way down to basics. With that being said on the attack side i am going with the MFA Fatigue attack as the team divided up attack types relevant to the app and company. With that being said I have the attached so far, but I feel like the banker side is not flowing correctly and the attack side is maybe to aggressive. With the andriod app access via ssl with user creds followed by mfa auth. The process is rather short, am I being to specific in my case?

Dr. Gandhi-  The "Android file access" is not really a feature of NextCloud. Perhaps the real actor is a "Bankers Android Phone". This way you can just invoke the login to Nextcloud with MFA usecase directly. The attacks you are listing on the other side can evolve as a result of <<threaten>> and <<prevent>> dependencies between usecases and misusecases.

Chris -Dr. Gandhi. Is the attached closer to what your looking for? I know it looks like a jumbled mess but I really tried to think about how the system works. Security built into what and how that would interact with the attacker, user and system.

Dr. Gandhi-  A few things to consider. Cyber Training is likely not a feature that is implemented in an application like NextCloud. So why is it a usecase? Usecases are features of the software application. Also NetCloud Mobile login usecase can be understood as a feature of the nextcloud server. So you don’t really need to separate it out. This will reduce your diagram complexity further.

**Comment by Chepburn-uno** [comment]
After conversing with Dr. Gandhi I arrived at draft 2 and asked that the team provide feedback which Tyler was the first to respond.  I made changes based off his recommendations.

**Comment by Chepburn-uno** [comment]
Draft1, 2 and 3 have been uploaded to GitHub and Draft 3 is ready for peer review. Marked the task as ready for peer review as well.

**Comment by lreichlinger** [comment]
Your Drafts look good Chris. Did you get a chance to write up your paragraphs for the use case? Could probably copy the outline @Hinrichsta had already setup to make it consistent.

**Comment by Chepburn-uno** [comment]
Do you know the name of the outline file? I did get my paragraphs done and some ideas for the teamwork section.

On Sep 23, 2023 1:38 PM, lreichlinger ***@***.***> wrote:
Non-NU Email
________________________________

Your Drafts look good Chris. Did you get a chance to write up your paragraphs for the use case? Could probably copy the outline @Hinrichsta<https://urldefense.com/v3/__https://github.com/Hinrichsta__;!!PvXuogZ4sRB2p-tU!GqkQw6Uqgu_5QN-uUwLZpoFVRUVAqI0-HtgjL9DXNwFka5v9o21ARKr0GppE7PLr20AeKP-7FSoEQddpC98k3Nz1YJ4$> had already setup to make it consistent.

**Comment by lreichlinger** [comment]
Hey Chris,

Sorry for the late response, I used the outline in the [Software Security Engineering.md](https://github.com/Hinrichsta/FA23-Cyber8420/blob/main/Software%20Security%20Engineering/Software%20Security%20Engineering.md)  file and you can see we both shared the same format. Please let me know if you have any questions.
