### ISSUE TITLE
Proposal Reflection for Assignment 2

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#32]
Everyone is creating their own individual reflection, which will then be compiled into one for the document.

**Comment by lreichlinger** [comment]
I have added my reflection to the Software Security Engineering.md file and we can compile them all tonight at 5PM.

**Comment by Hinrichsta** [comment]
I have my reflection in a personal word document and prepped for this evenings meeting
