### ISSUE TITLE
Create Software Assurance Diagram

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#39]

**Comment by lreichlinger** [comment]
Top-Claim C1: NextCloud eliminates unauthorized account access

**Comment by lreichlinger** [comment]
Added top level claim #2 to the Assurance Case.md file. will add text for description soon.

**Comment by lreichlinger** [comment]
Added context for Alignment and all Evidence explanations.

**Comment by lreichlinger** [comment]
Moved to peer review.

**Comment by Hinrichsta** [comment]
Probably don't need the undermine, since Dr. Gandhi stated we don't have to include the defeaters.  Everything else looks solid, and the undermine does work with the flow of it all.

**Comment by lreichlinger** [comment]
After discussing with group decided to keep Undermine in the diagram.
