### ISSUE TITLE
Create DFD

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#45]
Create a Data Flow Diagram based on your scenario from the last couple of Projects.

* Develop DFDs for critical data-flows through the software for your project.  
    * Recall the Security Requirements and Assurance Case Assignments. You prioritized several scenarios for building use/misuse cases and identify assurance claims. Develop DFDs that support each of your scenarios. It is OK to have DFDs that support multiple scenarios. 
    * Draw and analyze the DFDs using the [Microsoft Threat Modeling tool (TMT)Links to an external site.](https://aka.ms/threatmodelingtool)
        * Examine each automatically identified threat
        * Document mitigation strategies for the relevant threats
        * Pay special attention to elements that interact across threat boundaries
        * Generate a full HTML report using TMT
        * Host the HTML reports in your project github repo and link from your markdown submission.

**Comment by lreichlinger** [comment]
Created the DFD in Microsoft TMT and worked through it with professor and team. Uploaded a working version to the repo and will continue working on Friday at 5PM.

**Comment by Chepburn-uno** [comment]
As a team we created a single level 2 diagram with each team member working on their own segment.  My segment was the mobile app. I shared my tmt file with Hennri as we compiled into a single tmt file as a team.

**Comment by hallou225** [comment]
Worked on the database segment of the TMT. Reviewed each section as a team
