### ISSUE TITLE
Part 2, Observations

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#46]
* Using findings from the DFD-based threat analysis from part 1 of this assignment, review your OSS project for design-related issues. Summarize your observations, in particular, highlight the gaps.
* Include a link to your team's GitHub repository that shows your internal project task assignments and collaborations to finish this task. 
* Include a reflection of your teamwork for this assignment. What issues occurred? How did you resolve them? What did you plan to change moving forward?

**Comment by lreichlinger** [comment]
Added initial observations Ready for peer review.

**Comment by Chepburn-uno** [comment]
Checked over observations add a portion for up time .
