### ISSUE TITLE
Team Motivation

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#5]
Team motivation for selecting this project.

Chris Hepburn -- Looked over and made comments.

**Comment by Hinrichsta** [comment]
Changed mentions of Nextcloud to Nextcloud files.  Adjusted the final sentence to call it out specifically.

**Comment by Chepburn-uno** [comment]
Chris Hepburn -- Looked over and made comments.

**Comment by Hinrichsta** [comment]
Fixed issues
