### ISSUE TITLE
Mobile App Code Scanning

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#52]

**Comment by Chepburn-uno** [comment]
IT took a bit to work out how github interfaces with SNYK the scanning application but in the end I was able to use the community free version of SNYK and scan the nextcloud mobile app via github after forking the app to my own portal.

**Comment by Chepburn-uno** [comment]
It took a bit to work out how GitHub interfaces with SNYK the scanning application but in the end, I was able to use the community free version of SNYK and scan the nextcloud mobile app via GitHub after forking the app to my own portal.
