### ISSUE TITLE
List of Security Features

### ISSUE THREAD

**Issue by Hinrichsta** [Hinrichsta/FA23-Cyber8420#8]
Develop a list of security features in the software (Again, if there are none or very few, then re-evaluate your choice).

**Comment by scummings-tech** [comment]
GetFinHelp (GFH) Bank implemented the following security control features in the Software Development Lifecycle (SDLC):
(AC)**Access Controls 
(AU)**Audit Controls 
CM**Configuration Management
I.	Software Usage Restrictions
II.	User-Installed Software
IA**Identification and Authentication
IR**Incident Response
Maintenance Tools
MP**Media Protection
PE***Physical and Environment Protection
PL**System Security Plan
PM**Information Security Program Plan
PS**Access Agreements
RA**Risk Assessment Policy and Procedures
PS**Access Agreements
RA**Risk Assessment Policy and Procedures
SA-8** Security Engineering Principles
SC-1 System and Communication Protection Policy and Procedures
•	SC-50 Software-Enforced Separation and Policy Enforcement
SI System and Information Integrity Policy and Procedures
•	SI-7 Software, Firmware, and Information Integrity
8.19 Installation of software on operational systems CM-5, CM-7(4)*, CM-7(5)*, CM-11*

**Comment by scummings-tech** [comment]
Close out
